USE [master]
GO
/****** Object:  Database [QuanLySanTheThao]    Script Date: 10/1/2026 11:49:40 PM ******/
CREATE DATABASE [QuanLySanTheThao]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanLySanTheThao', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\QuanLySanTheThao.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QuanLySanTheThao_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\QuanLySanTheThao_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [QuanLySanTheThao] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLySanTheThao].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QuanLySanTheThao] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET ARITHABORT OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [QuanLySanTheThao] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QuanLySanTheThao] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QuanLySanTheThao] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QuanLySanTheThao] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QuanLySanTheThao] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QuanLySanTheThao] SET  MULTI_USER 
GO
ALTER DATABASE [QuanLySanTheThao] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QuanLySanTheThao] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QuanLySanTheThao] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QuanLySanTheThao] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QuanLySanTheThao] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [QuanLySanTheThao] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [QuanLySanTheThao] SET QUERY_STORE = ON
GO
ALTER DATABASE [QuanLySanTheThao] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [QuanLySanTheThao]
GO
/****** Object:  Table [dbo].[BANGGIA]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BANGGIA](
	[MaBangGia] [varchar](10) NOT NULL,
	[MaSan] [varchar](10) NOT NULL,
	[TuNgay] [date] NOT NULL,
	[DenNgay] [date] NULL,
 CONSTRAINT [PK_BANGGIA] PRIMARY KEY CLUSTERED 
(
	[MaBangGia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHINHSACH]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHINHSACH](
	[MaCS] [varchar](10) NOT NULL,
	[TenCS] [nvarchar](100) NOT NULL,
	[TyLeCoc] [decimal](5, 2) NULL,
	[TyLeHuy] [decimal](5, 2) NULL,
 CONSTRAINT [PK_CHINHSACH] PRIMARY KEY CLUSTERED 
(
	[MaCS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHITIETBANGGIA]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETBANGGIA](
	[MaCTGia] [varchar](10) NOT NULL,
	[MaBangGia] [varchar](10) NOT NULL,
	[KhungGio] [nvarchar](50) NULL,
	[DonGia] [decimal](18, 0) NOT NULL,
 CONSTRAINT [PK_CHITIETBANGGIA] PRIMARY KEY CLUSTERED 
(
	[MaCTGia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHITIETDATSAN]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETDATSAN](
	[MaCT] [varchar](10) NOT NULL,
	[MaPhieu] [varchar](10) NOT NULL,
	[MaSan] [varchar](10) NOT NULL,
	[GioBD] [datetime] NOT NULL,
	[GioKT] [datetime] NOT NULL,
 CONSTRAINT [PK_CHITIETDATSAN] PRIMARY KEY CLUSTERED 
(
	[MaCT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHUCNANG]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHUCNANG](
	[MaCN] [varchar](10) NOT NULL,
	[TenCN] [nvarchar](100) NOT NULL,
	[MoTa] [nvarchar](200) NULL,
 CONSTRAINT [PK_CHUCNANG] PRIMARY KEY CLUSTERED 
(
	[MaCN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_CHUCNANG_TenCN] UNIQUE NONCLUSTERED 
(
	[TenCN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GIAODICH]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GIAODICH](
	[MaGD] [varchar](10) NOT NULL,
	[MaPhieu] [varchar](10) NOT NULL,
	[LoaiGD] [nvarchar](20) NULL,
	[SoTien] [decimal](18, 0) NOT NULL,
	[PhuongThuc] [nvarchar](30) NULL,
 CONSTRAINT [PK_GIAODICH] PRIMARY KEY CLUSTERED 
(
	[MaGD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MaKH] [varchar](10) NOT NULL,
	[HoTen] [nvarchar](100) NOT NULL,
	[SDT] [varchar](15) NOT NULL,
	[Email] [varchar](100) NULL,
	[DiaChi] [nvarchar](200) NULL,
	[TrangThai] [nvarchar](20) NOT NULL,
	[MaTK] [varchar](10) NULL,
 CONSTRAINT [PK_KHACHHANG] PRIMARY KEY CLUSTERED 
(
	[MaKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_KHACHHANG_Email] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_KHACHHANG_SDT] UNIQUE NONCLUSTERED 
(
	[SDT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHUYENMAI]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHUYENMAI](
	[MaKM] [varchar](10) NOT NULL,
	[TenKM] [nvarchar](100) NOT NULL,
	[GiaTriGiam] [decimal](18, 0) NULL,
	[TuNgay] [date] NULL,
	[DenNgay] [date] NULL,
 CONSTRAINT [PK_KHUYENMAI] PRIMARY KEY CLUSTERED 
(
	[MaKM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LICHBAOTRI]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LICHBAOTRI](
	[MaBaoTri] [varchar](10) NOT NULL,
	[MaSan] [varchar](10) NOT NULL,
	[MaNV] [varchar](10) NOT NULL,
	[NgayBD] [datetime] NOT NULL,
	[NgayKT] [datetime] NOT NULL,
	[LyDo] [nvarchar](200) NULL,
 CONSTRAINT [PK_LICHBAOTRI] PRIMARY KEY CLUSTERED 
(
	[MaBaoTri] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MONTHETHAO]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MONTHETHAO](
	[MaMon] [varchar](10) NOT NULL,
	[TenMon] [nvarchar](50) NOT NULL,
	[MoTa] [nvarchar](200) NULL,
	[TrangThai] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_MONTHETHAO] PRIMARY KEY CLUSTERED 
(
	[MaMon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_MONTHETHAO_TenMon] UNIQUE NONCLUSTERED 
(
	[TenMon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MaNV] [varchar](10) NOT NULL,
	[HoTen] [nvarchar](100) NOT NULL,
	[SDT] [varchar](15) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[ChucVu] [nvarchar](50) NULL,
	[TrangThai] [nvarchar](20) NOT NULL,
	[MaTK] [varchar](10) NULL,
 CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED 
(
	[MaNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_NHANVIEN_Email] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_NHANVIEN_SDT] UNIQUE NONCLUSTERED 
(
	[SDT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEUDATSAN]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUDATSAN](
	[MaPhieu] [varchar](10) NOT NULL,
	[MaKH] [varchar](10) NOT NULL,
	[MaNV] [varchar](10) NULL,
	[MaKM] [varchar](10) NULL,
	[MaCS] [varchar](10) NULL,
	[TrangThai] [nvarchar](30) NULL,
 CONSTRAINT [PK_PHIEUDATSAN] PRIMARY KEY CLUSTERED 
(
	[MaPhieu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SAN]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SAN](
	[MaSan] [varchar](10) NOT NULL,
	[TenSan] [nvarchar](50) NOT NULL,
	[MaMon] [varchar](10) NOT NULL,
	[ViTri] [nvarchar](100) NULL,
	[TrangThai] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_SAN] PRIMARY KEY CLUSTERED 
(
	[MaSan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAIKHOAN]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAIKHOAN](
	[MaTK] [varchar](10) NOT NULL,
	[TenDangNhap] [varchar](50) NOT NULL,
	[MatKhau] [varchar](255) NOT NULL,
	[Email] [varchar](100) NULL,
	[TrangThai] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_TAIKHOAN] PRIMARY KEY CLUSTERED 
(
	[MaTK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_TAIKHOAN_Email] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_TAIKHOAN_TenDangNhap] UNIQUE NONCLUSTERED 
(
	[TenDangNhap] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAIKHOANVAITRO]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAIKHOANVAITRO](
	[MaTK] [varchar](10) NOT NULL,
	[MaVaiTro] [varchar](10) NOT NULL,
 CONSTRAINT [PK_TAIKHOANVAITRO] PRIMARY KEY CLUSTERED 
(
	[MaTK] ASC,
	[MaVaiTro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VAITRO]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VAITRO](
	[MaVaiTro] [varchar](10) NOT NULL,
	[TenVaiTro] [nvarchar](50) NOT NULL,
	[MoTa] [nvarchar](200) NULL,
 CONSTRAINT [PK_VAITRO] PRIMARY KEY CLUSTERED 
(
	[MaVaiTro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_VAITRO_TenVaiTro] UNIQUE NONCLUSTERED 
(
	[TenVaiTro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VAITROCHUCNANG]    Script Date: 10/1/2026 11:49:40 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VAITROCHUCNANG](
	[MaVaiTro] [varchar](10) NOT NULL,
	[MaCN] [varchar](10) NOT NULL,
 CONSTRAINT [PK_VAITROCHUCNANG] PRIMARY KEY CLUSTERED 
(
	[MaVaiTro] ASC,
	[MaCN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHITIETBANGGIA] ADD  DEFAULT ((0)) FOR [DonGia]
GO
ALTER TABLE [dbo].[GIAODICH] ADD  DEFAULT ((0)) FOR [SoTien]
GO
ALTER TABLE [dbo].[KHACHHANG] ADD  DEFAULT (N'Hoạt động') FOR [TrangThai]
GO
ALTER TABLE [dbo].[KHUYENMAI] ADD  DEFAULT ((0)) FOR [GiaTriGiam]
GO
ALTER TABLE [dbo].[MONTHETHAO] ADD  DEFAULT (N'Hoạt động') FOR [TrangThai]
GO
ALTER TABLE [dbo].[NHANVIEN] ADD  DEFAULT (N'Đang làm') FOR [TrangThai]
GO
ALTER TABLE [dbo].[SAN] ADD  DEFAULT (N'Hoạt động') FOR [TrangThai]
GO
ALTER TABLE [dbo].[TAIKHOAN] ADD  DEFAULT (N'Hoạt động') FOR [TrangThai]
GO
ALTER TABLE [dbo].[BANGGIA]  WITH CHECK ADD  CONSTRAINT [FK_BANGGIA_SAN] FOREIGN KEY([MaSan])
REFERENCES [dbo].[SAN] ([MaSan])
GO
ALTER TABLE [dbo].[BANGGIA] CHECK CONSTRAINT [FK_BANGGIA_SAN]
GO
ALTER TABLE [dbo].[CHITIETBANGGIA]  WITH CHECK ADD  CONSTRAINT [FK_CTBANGGIA_BANGGIA] FOREIGN KEY([MaBangGia])
REFERENCES [dbo].[BANGGIA] ([MaBangGia])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CHITIETBANGGIA] CHECK CONSTRAINT [FK_CTBANGGIA_BANGGIA]
GO
ALTER TABLE [dbo].[CHITIETDATSAN]  WITH CHECK ADD  CONSTRAINT [FK_CTDATSAN_PHIEU] FOREIGN KEY([MaPhieu])
REFERENCES [dbo].[PHIEUDATSAN] ([MaPhieu])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CHITIETDATSAN] CHECK CONSTRAINT [FK_CTDATSAN_PHIEU]
GO
ALTER TABLE [dbo].[CHITIETDATSAN]  WITH CHECK ADD  CONSTRAINT [FK_CTDATSAN_SAN] FOREIGN KEY([MaSan])
REFERENCES [dbo].[SAN] ([MaSan])
GO
ALTER TABLE [dbo].[CHITIETDATSAN] CHECK CONSTRAINT [FK_CTDATSAN_SAN]
GO
ALTER TABLE [dbo].[GIAODICH]  WITH CHECK ADD  CONSTRAINT [FK_GIAODICH_PHIEU] FOREIGN KEY([MaPhieu])
REFERENCES [dbo].[PHIEUDATSAN] ([MaPhieu])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[GIAODICH] CHECK CONSTRAINT [FK_GIAODICH_PHIEU]
GO
ALTER TABLE [dbo].[KHACHHANG]  WITH CHECK ADD  CONSTRAINT [FK_KHACHHANG_TAIKHOAN] FOREIGN KEY([MaTK])
REFERENCES [dbo].[TAIKHOAN] ([MaTK])
GO
ALTER TABLE [dbo].[KHACHHANG] CHECK CONSTRAINT [FK_KHACHHANG_TAIKHOAN]
GO
ALTER TABLE [dbo].[LICHBAOTRI]  WITH CHECK ADD  CONSTRAINT [FK_LICHBAOTRI_NHANVIEN] FOREIGN KEY([MaNV])
REFERENCES [dbo].[NHANVIEN] ([MaNV])
GO
ALTER TABLE [dbo].[LICHBAOTRI] CHECK CONSTRAINT [FK_LICHBAOTRI_NHANVIEN]
GO
ALTER TABLE [dbo].[LICHBAOTRI]  WITH CHECK ADD  CONSTRAINT [FK_LICHBAOTRI_SAN] FOREIGN KEY([MaSan])
REFERENCES [dbo].[SAN] ([MaSan])
GO
ALTER TABLE [dbo].[LICHBAOTRI] CHECK CONSTRAINT [FK_LICHBAOTRI_SAN]
GO
ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_NHANVIEN_TAIKHOAN] FOREIGN KEY([MaTK])
REFERENCES [dbo].[TAIKHOAN] ([MaTK])
GO
ALTER TABLE [dbo].[NHANVIEN] CHECK CONSTRAINT [FK_NHANVIEN_TAIKHOAN]
GO
ALTER TABLE [dbo].[PHIEUDATSAN]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUDATSAN_CHINHSACH] FOREIGN KEY([MaCS])
REFERENCES [dbo].[CHINHSACH] ([MaCS])
GO
ALTER TABLE [dbo].[PHIEUDATSAN] CHECK CONSTRAINT [FK_PHIEUDATSAN_CHINHSACH]
GO
ALTER TABLE [dbo].[PHIEUDATSAN]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUDATSAN_KHACHHANG] FOREIGN KEY([MaKH])
REFERENCES [dbo].[KHACHHANG] ([MaKH])
GO
ALTER TABLE [dbo].[PHIEUDATSAN] CHECK CONSTRAINT [FK_PHIEUDATSAN_KHACHHANG]
GO
ALTER TABLE [dbo].[PHIEUDATSAN]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUDATSAN_KHUYENMAI] FOREIGN KEY([MaKM])
REFERENCES [dbo].[KHUYENMAI] ([MaKM])
GO
ALTER TABLE [dbo].[PHIEUDATSAN] CHECK CONSTRAINT [FK_PHIEUDATSAN_KHUYENMAI]
GO
ALTER TABLE [dbo].[PHIEUDATSAN]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUDATSAN_NHANVIEN] FOREIGN KEY([MaNV])
REFERENCES [dbo].[NHANVIEN] ([MaNV])
GO
ALTER TABLE [dbo].[PHIEUDATSAN] CHECK CONSTRAINT [FK_PHIEUDATSAN_NHANVIEN]
GO
ALTER TABLE [dbo].[SAN]  WITH CHECK ADD  CONSTRAINT [FK_SAN_MONTHETHAO] FOREIGN KEY([MaMon])
REFERENCES [dbo].[MONTHETHAO] ([MaMon])
GO
ALTER TABLE [dbo].[SAN] CHECK CONSTRAINT [FK_SAN_MONTHETHAO]
GO
ALTER TABLE [dbo].[TAIKHOANVAITRO]  WITH CHECK ADD  CONSTRAINT [FK_TKVT_TAIKHOAN] FOREIGN KEY([MaTK])
REFERENCES [dbo].[TAIKHOAN] ([MaTK])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TAIKHOANVAITRO] CHECK CONSTRAINT [FK_TKVT_TAIKHOAN]
GO
ALTER TABLE [dbo].[TAIKHOANVAITRO]  WITH CHECK ADD  CONSTRAINT [FK_TKVT_VAITRO] FOREIGN KEY([MaVaiTro])
REFERENCES [dbo].[VAITRO] ([MaVaiTro])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TAIKHOANVAITRO] CHECK CONSTRAINT [FK_TKVT_VAITRO]
GO
ALTER TABLE [dbo].[VAITROCHUCNANG]  WITH CHECK ADD  CONSTRAINT [FK_VTCN_CHUCNANG] FOREIGN KEY([MaCN])
REFERENCES [dbo].[CHUCNANG] ([MaCN])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[VAITROCHUCNANG] CHECK CONSTRAINT [FK_VTCN_CHUCNANG]
GO
ALTER TABLE [dbo].[VAITROCHUCNANG]  WITH CHECK ADD  CONSTRAINT [FK_VTCN_VAITRO] FOREIGN KEY([MaVaiTro])
REFERENCES [dbo].[VAITRO] ([MaVaiTro])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[VAITROCHUCNANG] CHECK CONSTRAINT [FK_VTCN_VAITRO]
GO
ALTER TABLE [dbo].[CHINHSACH]  WITH CHECK ADD  CONSTRAINT [CK_CHINHSACH_TyLeCoc] CHECK  (([TyLeCoc]>=(0) AND [TyLeCoc]<=(100)))
GO
ALTER TABLE [dbo].[CHINHSACH] CHECK CONSTRAINT [CK_CHINHSACH_TyLeCoc]
GO
ALTER TABLE [dbo].[CHINHSACH]  WITH CHECK ADD  CONSTRAINT [CK_CHINHSACH_TyLeHuy] CHECK  (([TyLeHuy]>=(0) AND [TyLeHuy]<=(100)))
GO
ALTER TABLE [dbo].[CHINHSACH] CHECK CONSTRAINT [CK_CHINHSACH_TyLeHuy]
GO
ALTER TABLE [dbo].[CHITIETBANGGIA]  WITH CHECK ADD  CONSTRAINT [CK_CHITIETBANGGIA_DonGia] CHECK  (([DonGia]>=(0)))
GO
ALTER TABLE [dbo].[CHITIETBANGGIA] CHECK CONSTRAINT [CK_CHITIETBANGGIA_DonGia]
GO
ALTER TABLE [dbo].[CHITIETDATSAN]  WITH CHECK ADD  CONSTRAINT [CK_CHITIETDATSAN_ThoiGian] CHECK  (([GioBD]<[GioKT]))
GO
ALTER TABLE [dbo].[CHITIETDATSAN] CHECK CONSTRAINT [CK_CHITIETDATSAN_ThoiGian]
GO
ALTER TABLE [dbo].[GIAODICH]  WITH CHECK ADD  CONSTRAINT [CK_GIAODICH_SoTien] CHECK  (([SoTien]>=(0)))
GO
ALTER TABLE [dbo].[GIAODICH] CHECK CONSTRAINT [CK_GIAODICH_SoTien]
GO
ALTER TABLE [dbo].[KHUYENMAI]  WITH CHECK ADD  CONSTRAINT [CK_KHUYENMAI_GiaTriGiam] CHECK  (([GiaTriGiam]>=(0)))
GO
ALTER TABLE [dbo].[KHUYENMAI] CHECK CONSTRAINT [CK_KHUYENMAI_GiaTriGiam]
GO
ALTER TABLE [dbo].[LICHBAOTRI]  WITH CHECK ADD  CONSTRAINT [CK_LICHBAOTRI_ThoiGian] CHECK  (([NgayBD]<[NgayKT]))
GO
ALTER TABLE [dbo].[LICHBAOTRI] CHECK CONSTRAINT [CK_LICHBAOTRI_ThoiGian]
GO
USE [master]
GO
ALTER DATABASE [QuanLySanTheThao] SET  READ_WRITE 
GO
